import {createDanceMoves,createMemoryPageStore,fromWordPressMeta,type DanceMoves} from '@kieransimkin/dancemoves';
import {useDanceMoves,PageMetadataEditor} from '@kieransimkin/dancemoves/react';
import {createCaptureHandler,createDownloadService,validateTimingFile} from '@kieransimkin/dancemoves/server';
const root = document.createElement('section');
const audio = document.createElement('audio');
root.append(audio);
const motion: DanceMoves = createDanceMoves({root,bpm:145,diagnostics:true});
motion.onEveryBeat(detail => console.log(detail.boundaryTick));
motion.effects.pointer({root,target:root}).reset();
motion.effects.playbackPulse({root,audio}).sync();
motion.applyCatalogueTiming?.();
motion.createOrientation({render(point){console.log(point.x,point.y);}}).disable();
motion.rudiments.animate({id:'types:motion',root,target:root,rudiment:'clay_background',audio,clock:'audio'}).destroy();
const store = createMemoryPageStore();
store.save('arcadians',{bpm:145});
void fromWordPressMeta({_dance_moves_bpm:145});
validateTimingFile('[00:00.00]INTRO',{kind:'cue',filename:'sections.cue'});
const download=createDownloadService({rootDirectory:'/private/media',origin:'https://example.test',secret:'a'.repeat(32)});
void download.handle(new Request(download.sign('track.mp3')));
const capture=createCaptureHandler({allowedOrigin:'https://example.test',authorize:()=>true,rateLimit:()=>true,store:async()=>({captureId:'demo',storedPrivately:true})});
void capture(new Request('https://example.test/api/capture',{method:'POST'}));
void useDanceMoves;void PageMetadataEditor;
motion.destroy();
