import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
import {environment,Element} from './fake-dom.mjs';import {createScope} from '../../src/scope.mjs';import {transformOwnedOperations} from '../../tools/build-modules.mjs';
function install(file,scope){let source=fs.readFileSync(new URL('../../'+file,import.meta.url),'utf8');if(file.endsWith('dance-moves-rudiments.js'))source=source.replace('const token = String(++serial);','const token = __dmScope.id + "-" + String(++serial);');const code=transformOwnedOperations(source,file);const factory=vm.runInNewContext('(function(__dmScope){const window=__dmScope.window,document=__dmScope.document;const module=undefined;const {CustomEvent,MutationObserver,ResizeObserver,IntersectionObserver,setTimeout,clearTimeout,requestAnimationFrame,cancelAnimationFrame}=window;'+code+'\n})',{console});factory(scope);}
function core(scope){scope.window.DanceMoves={version:'3.0.0',bpm:145,currentTick:()=>scope.window.performance.now()*145*16/60000,durationMilliseconds:t=>t*3750/145,onCue:()=>()=>{}};}
test('scope does not patch global window or another root',()=>{const e=environment(),b=new Element(e.doc);e.doc.body.append(b);const a=createScope(e.root,{bpm:145}),c=createScope(b,{bpm:90});a.window.DanceMoves={bpm:145};assert.equal(e.host.DanceMoves,undefined);assert.equal(c.window.DanceMoves,undefined);assert.equal(a.document.querySelector('.ks-epk'),e.root);a.dispose();assert.equal(c.document.querySelector('.ks-epk'),b);c.dispose();});
test('listeners, media callbacks, timers, frames and observers are released',()=>{const e=environment(),s=createScope(e.root,{});let count=0;s.listen(e.root,'play',()=>count++);s.window.requestAnimationFrame(()=>count++);s.window.setTimeout(()=>count++,5);const observer=new s.window.MutationObserver(()=>count++);observer.observe(e.root);e.root.dispatchEvent(new Event('play'));assert.equal(count,1);s.dispose();e.root.dispatchEvent(new Event('play'));e.advance();assert.equal(count,1);assert.equal(e.frames.size,0);assert.equal(e.timers.size,0);assert.equal(observer.disconnected,true);assert.equal(s.snapshot().listeners,0);});
test('once listeners can be registered again after firing',()=>{const e=environment(),s=createScope(e.root,{});let n=0;const f=()=>n++;s.listen(e.root,'play',f,{once:true});e.root.dispatchEvent(new Event('play'));s.listen(e.root,'play',f,{once:true});e.root.dispatchEvent(new Event('play'));assert.equal(n,2);s.dispose();});
test('restore owned styles/attributes without erasing later host writes',()=>{const e=environment();e.root.style.setProperty('--x','before');const s=createScope(e.root,{});s.setStyle(e.root.style,'--x','during');s.setStyle(e.root.style,'--y','owned');e.root.style.setProperty('--y','host');s.dataset(e.root,'hello','owned');s.dispose();assert.equal(e.root.style.getPropertyValue('--x'),'before');assert.equal(e.root.style.getPropertyValue('--y'),'host');assert.equal(e.root.hasAttribute('data-hello'),false);assert.equal(e.root.classList.contains('ks-epk'),false);});
test('legacy aliases are restored on destroy',()=>{const e=environment();const original={previous:true};e.host.DanceMoves=original;const s=createScope(e.root,{}, {legacyGlobals:true});s.window.DanceMoves={mounted:true};assert.equal(e.host.DanceMoves.mounted,true);s.dispose();assert.equal(e.host.DanceMoves,original);});
test('pending continuations and requests cannot remount after cleanup',async()=>{const e=environment(),s=createScope(e.root,{});let resolve,n=0;const pending=new Promise(r=>resolve=r);const next=s.chain(pending,'then',()=>n++);s.dispose();resolve();await next;assert.equal(n,0);await assert.rejects(s.window.fetch('/anything'));});
test('compiler instruments anonymous DOM ownership without eval in output',()=>{const output=transformOwnedOperations('audio.addEventListener("play", ()=>{}); style.setProperty("--x", "1"); root.style.transform="none";root.dataset.ready="1";root.classList.add("on");delete root.dataset.ready;','demo');for(const name of ['listen','setStyle','dataset','classes'])assert.match(output,new RegExp('__dmScope\\.'+name));assert.doesNotMatch(output,/\beval\(|new Function/);});
test('actual native backend with transformed rudiment runtime',async()=>{const e=environment(),s=createScope(e.root,{bpm:145});core(s);install('assets/vendor/dancerudiments/dancerudiments-native.js',s);install('assets/dance-moves-rudiments.js',s);const r=s.window.DanceMovesRudiments;await r.ready();assert.equal(r.catalogue().length,15);assert.equal(r.sample('clay_background',256).x,r.sample('clay_background',0).x);const target=new Element(e.doc);e.root.append(target);const handle=r.animate({id:'test',root:e.root,target,rudiment:'sway',clock:'page',css:false});await handle.ready;e.advance();assert.equal(handle.snapshot().status,'running');r.destroyAll();s.dispose();assert.equal(e.frames.size,0);assert.equal(s.snapshot().listeners,0);});
test('two native CSS owners receive independent selectors',async()=>{const e=environment(),second=new Element(e.doc);e.doc.body.append(second);const scopes=[createScope(e.root,{bpm:145}),createScope(second,{bpm:90})];const tokens=[];for(const s of scopes){core(s);install('assets/vendor/dancerudiments/dancerudiments-native.js',s);install('assets/dance-moves-rudiments.js',s);const target=new Element(e.doc);s.document.documentElement.append(target);const handle=s.window.DanceMovesRudiments.animate({id:'same-local-id',root:s.document.documentElement,target,rudiment:'clay_background'});await handle.ready;tokens.push(target.getAttribute('data-dance-moves-rudiment-owner'));}assert.notEqual(tokens[0],tokens[1]);for(const s of scopes){s.window.DanceMovesRudiments.destroyAll();s.dispose();}assert.equal(e.doc.head.children.length,0);});
test('actual effects registry is per mount and can tear down',()=>{const e=environment(),s=createScope(e.root,{});core(s);install('assets/dance-moves-effects.js',s);const effects=s.window.DanceMovesEffects;assert.equal(effects.snapshot().length,0);const q=effects.quality({id:'quality',root:e.root});assert.equal(effects.snapshot().length,1);q.teardown();assert.equal(effects.snapshot().length,0);s.dispose();assert.equal(e.frames.size,0);});
