'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const manifest = JSON.parse(fs.readFileSync(path.join(__dirname, 'harness/california-screamin/california-screamin.json'), 'utf8'));
const php = fs.readFileSync(path.join(root, 'kieran-epk-device-orientation.php'), 'utf8');
const parameters = manifest.parameters;
assert.deepEqual(new Set(parameters.map(item => item.group)), new Set(['master', 'timing', 'effect']), 'California must satisfy all required harness groups');
assert.equal(new Set(parameters.map(item => item.id)).size, parameters.length, 'parameter IDs are unique');
const cadence = parameters.find(item => item.id === 'orientation-target-ticks');
assert.ok(cadence, 'a real effect reference is present, not an empty placeholder group');
assert.equal(cadence.type, 'readonly');
assert.equal(cadence.apply, 'readonly');
assert.equal(cadence.target, 'ksEpkOrientationConfig.transitionTargetTicks');
const configured = php.match(/'transitionTargetTicks'\s*=>\s*(\d+)\s*,/);
assert.ok(configured, 'production orientation configuration declares its target cadence');
assert.equal(cadence.default, Number(configured[1]), 'the displayed cadence must match production');
assert.equal(parameters.find(item => item.id === 'effect-enabled').group, 'master');
assert.equal(parameters.find(item => item.id === 'production-bpm').default, manifest.release.bpm);
console.log('PASS California harness parameter groups and production cadence (10 checks).');
