'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { fixture } = require('./rudiments-runtime.test.cjs');
const source = fs.readFileSync(path.join(__dirname,'../assets/clay-stars-rudiments.js'),'utf8');
function mount(noWasm = false) {
  const f = fixture(noWasm);
  const state = { destroyed:false, settings:{enabled:true}, performance:{profile:'full'} };
  const accent = { animationName:'ks-clay-rudiment-treatment', playState:'paused', currentTime:0 };
  f.root.querySelector = selector => selector === '.epk-atmosphere' ? f.target : selector === 'audio' ? f.audio : null;
  f.target.getAnimations = () => [accent];
  const query = f.doc.querySelector.bind(f.doc);
  f.doc.querySelector = selector => selector === '.ks-epk.ks-clay-stars-v2' ? f.root : query(selector);
  f.win.CSS = { supports: () => true };
  f.win.DanceMovesClayStars = { root:f.root, snapshot:() => state };
  vm.runInNewContext(source, { window:f.win, document:f.doc, console });
  f.notify = () => f.observers.filter(o => !o.disconnected && o.kind === 'mutation').forEach(o => o.fn([]));
  return { ...f, state, accent };
}
(async () => {
  const f = mount(); const api = f.win.DanceMovesRudiments;
  await api.get('clay-stars:background-rudiment').ready;
  await new Promise(setImmediate);
  assert.equal(f.root.getAttribute('data-dance-moves-rudiment-clay'),'active');
  assert.equal(api.snapshot().instances.length,1);
  f.setTicks(50); f.frame();
  const c = f.win.DanceMovesClayRudiment.snapshot().controller;
  assert.equal(c.pip,100); assert.equal(c.position.x,-14);
  assert.ok(Math.abs(f.accent.currentTime - 100 / 256 * 60000 / 90 * 8)<1e-8);
  assert.equal(f.accent.playState,'paused');
  console.log('PASS Clay native amplitude, eight-beat cadence and shared companion phase');
  f.state.performance.profile='constrained'; f.notify();
  assert.equal(f.root.getAttribute('data-dance-moves-rudiment-clay'),'suspended');
  assert.equal(f.frames.size,0);
  f.state.performance.profile='minimal'; f.notify(); assert.equal(f.frames.size,0);
  f.setTicks(84.5); f.state.performance.profile='full'; f.notify();
  assert.equal(api.get('clay-stars:background-rudiment').snapshot().pip,169);
  console.log('PASS constrained/minimal suspension and current-position full-tier recovery');
  f.state.settings.enabled=false; f.notify(); assert.equal(f.frames.size,0);
  f.state.settings.enabled=true; f.notify(); assert.equal(f.frames.size,1);
  f.state.destroyed=true; f.notify();
  assert.equal(f.win.DanceMovesClayRudiment.snapshot().status,'destroyed');
  assert.equal(api.snapshot().instances.length,0);
  assert.equal(f.root.hasAttribute('data-dance-moves-rudiment-clay'),false);
  assert.equal(f.frames.size,0);
  console.log('PASS legacy runtime disable and teardown release native resources');
  const bad=mount(true);
  await assert.rejects(bad.win.DanceMovesRudiments.ready());
  await new Promise(setImmediate);
  assert.equal(bad.win.DanceMovesClayRudiment.snapshot().status,'fallback');
  assert.equal(bad.win.DanceMovesRudiments.snapshot().instances.length,0);
  assert.equal(bad.frames.size,0);
  assert.equal(bad.root.getAttribute('data-dance-moves-rudiment-clay'),'fallback');
  console.log('PASS Clay WASM failure leaves the non-overridden legacy path and no orphan controller');
  console.log('Completed 20 Clay adapter assertions (mock DOM, real WASM)');
})().catch(error => { console.error(error); process.exitCode=1; });
