const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname,'..');
const js = fs.readFileSync(path.join(root,'assets','paper-dreams-flight.js'),'utf8');
const css = fs.readFileSync(path.join(root,'assets','paper-dreams-flight.css'),'utf8');
const php = fs.readFileSync(path.join(root,'kieran-epk-device-orientation.php'),'utf8');
assert.doesNotMatch(php,/DANCE_MOVES_PAPER_DREAMS_PAGE_ID/);
assert.match(php,/DANCE_MOVES_META_EFFECT', '_dance_moves_effect'/);
assert.match(php,/'paper-planes' === \$config\['effect'\]/);
assert.match(php,/'bpm' => \$config\['bpm'\]/);
assert.doesNotMatch(js,/\[data-release="paper-dreams-from-the-sky"\]/);
for (const phase of ['glide','climb','mush','stall','drop','recovery','swoop']) assert.match(js,new RegExp('\\b'+phase+'\\b'));
assert.match(js,/motion\.currentTick/);
assert.match(js,/IntersectionObserver/);
assert.match(js,/document\.hidden/);
assert.match(js,/compactPlaneCount/);
assert.doesNotMatch(js,/style\.(?:top|left|width|height)\s*=/);
assert.match(css,/prefers-reduced-motion:reduce/);
assert.match(css,/forced-colors:active/);
assert.doesNotMatch(css,/position:fixed/);
assert.doesNotMatch(css,/(?:brightness|background-color|opacity).*animation/i);
console.log('Page-configured bounded paper-plane flight contracts passed.');
