'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { pinnedTextBytes } = require('../tools/rudiments-source-integrity.cjs');
const root = path.resolve(__dirname, '..');
const read = p => fs.readFileSync(path.join(root,p),'utf8');
const runtime = read('assets/dance-moves-rudiments.js');
const adapter = read('assets/clay-stars-rudiments.js');
const css = read('assets/clay-stars-rudiments.css');
assert.doesNotMatch(runtime, /Math\.(?:sin|cos)|clay_keys|stroke_envelope|smooth\(/, 'no JS motion implementation');
assert.match(runtime, /native\.dr_sample/);
assert.match(runtime, /rule\.style\.setProperty/);
assert.doesNotMatch(runtime, /target\.style\./, 'no per-frame inline styles');
assert.doesNotMatch(runtime, /setInterval|setTimeout/, 'no independent timer clock');
assert.match(adapter, /rate: 0\.5/);
assert.match(adapter, /amplitude: \{ x: 14, y: 10, z: 0 \}/);
assert.match(adapter, /accents\.currentTime = detail\.loopProgress \* detail\.durationMilliseconds/);
assert.match(adapter, /snapshot\(\)\.destroyed/);
assert.match(adapter, /controller\.destroy\(\)/);
assert.match(css, /animation-play-state: paused !important/);
const keyframes = css.slice(css.indexOf('@keyframes'), css.indexOf('@media'));
assert.doesNotMatch(keyframes, /translate|background|filter/, 'page accents must not recreate position or full-frame colour');
assert.match(css, /prefers-reduced-motion: reduce/);
assert.match(css, /forced-colors: active/);
const pin = JSON.parse(read('vendor/dancerudiments/UPSTREAM.json'));
for (const name of ['vendor/dancerudiments/LICENSE', 'assets/vendor/dancerudiments/LICENSE']) {
  pinnedTextBytes(fs.readFileSync(path.join(root, name)), pin.files.LICENSE, name);
}
console.log('PASS 15 source ownership, cadence, CSS, fallback and licence contracts');
